const repo = require("../repository")
const {CustomError} = require("../config/error")


exports.requestFriend = async(req,res,next) =>{
    try{
        
    }catch(err){
        next(err)
    }
}

